[workspace]
resolver = "1"
members = [
    "typebridge",
    "typebridge-macro"
]

[workspace.dependencies]
typebridge_macro = {path = "typebridge-macro"}

syn = { version = "2.0.90", features = ["full", "extra-traits"] }
quote = "1.0"
serde = "1.0.216"